[tool.black]
line-length = 100

[tool.pylint]
generated-members = ["torch.*"]
disable = [
  "missing-module-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
  "invalid-name",
]
